### ISSUE TITLE
Anything I can help with?

### ISSUE THREAD

**Issue by TomKriek** [thirtybees/postnl-api-php#3]
Greetings, I have been looking for an implementation like this for a while now. I noticed you said this was in it's development stage and was wondering if there are any things you require help with?

I've been seeing some "FIXME"s in the code itself but no context what needs to be fixed. Is there any kind of planning on placing issues here with the "help wanted" tag so other people can contribute to this project?

**Comment by firstred** [comment]
Greetings and thanks for the offer, appreciate it!

>  Is there any kind of planning on placing issues here with the "help wanted" tag so other people can contribute to this project?

Not at the moment, but we can make that happen. Please allow us a few days so we can sort things out. 
At the moment we are looking at possibilities to integrate with the MyParcel API as well. It can provide a few extras such as webhooks. It seems that you can convert your CIF keys on this site: https://postnl-plugins.nl/

More info will follow shortly!
