### ISSUE TITLE
Error when downloading "Easy Return" label

### ISSUE THREAD

**Issue by chris102948** [thirtybees/postnl-api-php#41]
When creating an Easy Return label (productcode 4910 for PostNL) we noticed that we're unable to download the label. It will give an error:

PHP Fatal error: Uncaught Error: Cannot use object of type setasign\Fpdi\PdfParser\StreamReader as array in firstred/postnl-api-php/src/PostNL.php:956

I'm not 100% sure if it is related to Fpdi or to this PostNL lib, but we've created a patch with some changes that fixes the issue for us. I've attached it.

[patches_RT-381.txt](https://github.com/firstred/postnl-api-php/files/6754158/patches_RT-381.txt)

**Comment by firstred** [comment]
Thanks for opening this issue and sharing the (possible) solution!

I'll try to verify the changes and add it to the next release.

**Comment by firstred** [comment]
I have applied the patch. Thanks a lot!
