### ISSUE TITLE
PostNL::getLocation no longer returns a single location and the LocationCode relevant data gets stripped.

### ISSUE THREAD

**Issue by TomKriek** [thirtybees/postnl-api-php#42]
Been wracking my head around this one for 4 hours now but it seems that the getLocation function somehow misses the correct data from the response and strips it. It works fine in the getNearestLocations function but somehow zoning in on the single Location it's missing data.

I've been stepping through it with XDebug and it seems that in the `AbstractEntity::jsonDeserialize` functionality it doesn't copy over the ResponseLocation correctly to the $object, it's visible in the response but it gets stripped somewhere in there.

**Comment by firstred** [comment]
Do you still have a copy of the input data?

**Comment by firstred** [comment]
Response data, that is. If we can input the same data in the deserializer it should be easy to find a fix, I think.

**Comment by firstred** [comment]
I have applied the pull requests. Thanks a lot for opening this issue!
