### ISSUE TITLE
EORI number missing from Customs

### ISSUE THREAD

**Issue by lenvanessen** [thirtybees/postnl-api-php#52]
PostNL is releasing a new version of their api, so the eori number can be provided. Pr incoming

**Comment by lenvanessen** [comment]
Nevermind, it's ImporterReferenceCode and already implemented

**Comment by firstred** [comment]
Thanks! Do you think that this should be clarified in the documentation?

**Comment by lenvanessen** [comment]
@firstred  i believe it's missing from the docs:
https://github.com/firstred/postnl-api-php/blob/v1.3.x/docs/reference/Entity/Customs.rst

**Comment by firstred** [comment]
Thanks! The documentation has been updated.
