### ISSUE TITLE
CustomerCode used in generateBarcode request is not being used, default CustomerCode from the Customer is used instead.

### ISSUE THREAD

**Issue by daniel-memo-ict** [thirtybees/postnl-api-php#56]
Hey. 

We're trying to generate a barcode for a return label, which uses a different CustomerCode. We use this return customer code in a call to generateBarcode, however, the BarcodeService always uses the default CustomerCode from the Customer object, instead of the barcode that was set on the Barcode object.

https://github.com/firstred/postnl-api-php/blob/b2edfac5cc19f8a9f084945e0aef3db714d9c02d/src/Service/BarcodeService.php#L222

**Comment by firstred** [comment]
This is by design. Sending as a different customer requires either a newly instantiated `PostNL` object or `PostNL::setCustomer` needs to be called before generating a barcode.
