### ISSUE TITLE
Undefined array key "Shipping" in /vendor/firstred/postnl-api-php/src/Service/AbstractService.php:159

### ISSUE THREAD

**Issue by BBrunekreeft** [thirtybees/postnl-api-php#61]
When an invalid address is provided while sending shipments (`$postnl->sendShipments()`) an error is thrown:
`Undefined array key "Shipping" in /vendor/firstred/postnl-api-php/src/Service/AbstractService.php:159`

**Comment by firstred** [comment]
Solved by https://github.com/firstred/postnl-api-php/pull/62
