### ISSUE TITLE
The option 'Remark' within address does not work

### ISSUE THREAD

**Issue by paruzzi** [thirtybees/postnl-api-php#7]
I'm making labels with  'generateLabel'. 
All the recipient address details can be added, but 'Remarks' field does not work (is not show on my label)

`$label = $postnl->generateLabel(
    Shipment::create()
        ->setAddresses([
            Address::create([
                'AddressType' => '01',
                'CompanyName' => $Bedrijfsnaam,
                'Name'        => $Klantnaam,
                'Street'      => $Straat,
                'HouseNr'     => $Huisnummer,
                'HouseNrExt'  => $Toevoeging,
                'Zipcode'     => $Postcode,
                'City'        => $Plaats,
                'Countrycode' => $Land,
                'Remark'       => $Opmerking,
            ]),
        ])
        ->setBarcode($barcode)
        ->setDeliveryAddress('01')
        ->setDimension(new Dimension($Gewicht))
        ->setProductCodeDelivery($SoortZending),
    'Zebra|GK420d',
    true
);
`

**Comment by paruzzi** [comment]
oops, my mistake, shuld have used the code below : 
`
$label = $postnl->generateLabel(
    Shipment::create()
        ->setAddresses([
            Address::create([
                'AddressType' => '01',
                'CompanyName' => $Bedrijfsnaam,
                'Name'        => $Klantnaam,
                'Street'      => $Straat,
                'HouseNr'     => $Huisnummer,
                'HouseNrExt'  => $Toevoeging,
                'Zipcode'     => $Postcode,
                'City'        => $Plaats,
                'Countrycode' => $Land,
            ]),
        ])
        ->setRemark($Opmerking)
        ->setBarcode($barcode)
        ->setDeliveryAddress('01')
        ->setDimension(new Dimension($Gewicht))
        ->setProductCodeDelivery($SoortZending),
    'Zebra|GK420d',
    true
);
`

**Comment by firstred** [comment]
Hi @paruzzi 

Thanks for stopping by and great you figured it out!
Indeed, `Remark` is not part of the Shipment itself but belongs to a label.
