### ISSUE TITLE
GenerateLabels: TypeError about null in PendingPromise.php

### ISSUE THREAD

**Issue by eaibizz** [thirtybees/postnl-api-php#77]
Hello FirstRed developer(s),

When calling `generateLabels()` like in [the example](https://postnl-php.readthedocs.io/en/latest/sendandtrackshipments.html#generate-multiple-shipment-labels) here, I got the error below.
I'm using the latest v1.3.18 tag of the package.
The basic implementation that I've done is to send a single shipment to PostNL and then a label is generated with the address label in the middle of the A4 document.

Now the customer wants to print multiple labels on a single page, so that's the reason that I'd like to call `generateLabels`  to be able to receive a PDF document with 4 labels on a page.

The code I'm using is:
```
$shipments[] = Shipment::create([
            'Addresses' => [
                Address::create([
                    'AddressType' => '01',
                    'City' => $deliveryAddress->getPlace(),
                    'CountryCode' => $deliveryAddress->getCountryEntity()->getCodeShort() ?? "NL",
                    'FirstName' => $deliveryContact->getFirstname(),
                    'HouseNr' => $deliveryAddress->getHousenumber(),
                    'HouseNrExt' => $deliveryAddress->getHousenumberSuffix(),
                    'Name' => $deliveryContact->getLastname(),
                    'Street' => $deliveryAddress->getStreet(),
                    'Zipcode' => $deliveryAddress->getZipcode(),
                ]),
            ],
            'Barcode' => $barcode,
            'Dimension' => new Dimension('1000'),
            'ProductCodeDelivery' => $shipmentpackageEntity->getCode(),
        ]);

$Label = $postnl->generateLabels(
                $shipments,
                'GraphicFile|PDF',
                true,
                true,
                Label::FORMAT_A4,
                [
                    1 => true,
                    2 => true,
                    3 => true,
                    4 => true,
                ]
            );
```

This is the error:

<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/PendingPromise.php on line <i>232</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/PendingPromise.php on line <i>232</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>372152</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/projects/example-project-v1/src/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0039</td><td bgcolor='#eeeeec' align='right'>892288</td><td bgcolor='#eeeeec'>Bootstrap->__construct( <span>$autorun = </span>??? )</td><td title='/projects/example-project-v1/src/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>17</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0167</td><td bgcolor='#eeeeec' align='right'>4657112</td><td bgcolor='#eeeeec'>Bootstrap->run(  )</td><td title='/projects/example-project-v1/src/vendor/studioibizz/framework/src/classes/core/Bootstrap.php' bgcolor='#eeeeec'>.../Bootstrap.php<b>:</b>69</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0626</td><td bgcolor='#eeeeec' align='right'>7246656</td><td bgcolor='#eeeeec'>Controller->bulkActions(  )</td><td title='/projects/example-project-v1/src/vendor/studioibizz/framework/src/classes/core/Bootstrap.php' bgcolor='#eeeeec'>.../Bootstrap.php<b>:</b>665</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0649</td><td bgcolor='#eeeeec' align='right'>7267224</td><td bgcolor='#eeeeec'>CheckoutBulkController->generateLabelPostNL(  )</td><td title='/projects/example-project-v1/src/vendor/studioibizz/framework/src/classes/bases/Controller.php' bgcolor='#eeeeec'>.../Controller.php<b>:</b>2154</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.0684</td><td bgcolor='#eeeeec' align='right'>7295520</td><td bgcolor='#eeeeec'>ShipmentMapper::generateMultiLabel( <span>$shipmentEntities = </span><span>[0 =&gt; class ShipmentEntity { protected $object = &#39;Shipment&#39;; protected $id = &#39;2&#39;; protected $version_date = &#39;2023-03-22 14:58:05&#39;; protected $version_user = &#39;Current User&#39;; protected $owner = NULL; protected $state = &#39;Online&#39;; protected $language = &#39;nl_NL&#39;; protected $shipment_id = NULL; protected $checkout_id = &#39;333066&#39;; protected $shipment_date = &#39;2023-01-27 11:30:06&#39;; protected $shipment_reference = &#39;SHIPMENT20232016x1&#39;; protected $shipmentnumber = &#39;3SAFWK987454071&#39;; protected $label_url = NULL; protected $tracktrace_url = NULL; protected $big_parcel = &#39;N&#39;; protected $only_recipient = &#39;N&#39;; protected $signature = &#39;N&#39;; protected $return_not_home = &#39;N&#39;; protected $age_check = &#39;N&#39;; protected $insured_amount = &#39;0.00&#39;; protected $shipment_state = &#39;REGISTERED&#39;; public $insert = FALSE; public $is_dummy = FALSE; protected $subitems = NULL; protected $pagebuilder_use = NULL; protected $content_pattern = &#39;/&lt;(h\\d|p|ul|ol|blockquote)(\\s[^&gt;]*|&gt;)(.*?)&lt;\\/(p|ul|ol)&gt;/s&#39;; protected $kind = &#39;default&#39;; protected $item_url = [...]; protected $Refines = [...]; protected $RefinesByGroup = [...]; protected $Images = [...]; protected $encoded_id = NULL; protected $active_extensions = [...]; protected $custom_screen_folder = NULL }, 1 =&gt; class ShipmentEntity { protected $object = &#39;Shipment&#39;; protected $id = &#39;3&#39;; protected $version_date = &#39;2023-03-22 14:58:06&#39;; protected $version_user = &#39;Current User&#39;; protected $owner = NULL; protected $state = &#39;Online&#39;; protected $language = &#39;nl_NL&#39;; protected $shipment_id = NULL; protected $checkout_id = &#39;333062&#39;; protected $shipment_date = &#39;2023-01-27 11:30:06&#39;; protected $shipment_reference = &#39;SHIPMENT20232015x1&#39;; protected $shipmentnumber = &#39;3SAFWK987419796&#39;; protected $label_url = NULL; protected $tracktrace_url = NULL; protected $big_parcel = &#39;N&#39;; protected $only_recipient = &#39;N&#39;; protected $signature = &#39;N&#39;; protected $return_not_home = &#39;N&#39;; protected $age_check = &#39;N&#39;; protected $insured_amount = &#39;0.00&#39;; protected $shipment_state = &#39;REGISTERED&#39;; public $insert = FALSE; public $is_dummy = FALSE; protected $subitems = NULL; protected $pagebuilder_use = NULL; protected $content_pattern = &#39;/&lt;(h\\d|p|ul|ol|blockquote)(\\s[^&gt;]*|&gt;)(.*?)&lt;\\/(p|ul|ol)&gt;/s&#39;; protected $kind = &#39;default&#39;; protected $item_url = [...]; protected $Refines = [...]; protected $RefinesByGroup = [...]; protected $Images = [...]; protected $encoded_id = NULL; protected $active_extensions = [...]; protected $custom_screen_folder = NULL }, 2 =&gt; class ShipmentEntity { protected $object = &#39;Shipment&#39;; protected $id = &#39;4&#39;; protected $version_date = &#39;2023-03-22 14:58:06&#39;; protected $version_user = &#39;Current User&#39;; protected $owner = NULL; protected $state = &#39;Online&#39;; protected $language = &#39;nl_NL&#39;; protected $shipment_id = NULL; protected $checkout_id = &#39;333061&#39;; protected $shipment_date = &#39;2023-01-27 11:30:06&#39;; protected $shipment_reference = &#39;SHIPMENT20232014x1&#39;; protected $shipmentnumber = &#39;3SAFWK987447787&#39;; protected $label_url = NULL; protected $tracktrace_url = NULL; protected $big_parcel = &#39;N&#39;; protected $only_recipient = &#39;N&#39;; protected $signature = &#39;N&#39;; protected $return_not_home = &#39;N&#39;; protected $age_check = &#39;N&#39;; protected $insured_amount = &#39;0.00&#39;; protected $shipment_state = &#39;REGISTERED&#39;; public $insert = FALSE; public $is_dummy = FALSE; protected $subitems = NULL; protected $pagebuilder_use = NULL; protected $content_pattern = &#39;/&lt;(h\\d|p|ul|ol|blockquote)(\\s[^&gt;]*|&gt;)(.*?)&lt;\\/(p|ul|ol)&gt;/s&#39;; protected $kind = &#39;default&#39;; protected $item_url = [...]; protected $Refines = [...]; protected $RefinesByGroup = [...]; protected $Images = [...]; protected $encoded_id = NULL; protected $active_extensions = [...]; protected $custom_screen_folder = NULL }, 3 =&gt; class ShipmentEntity { protected $object = &#39;Shipment&#39;; protected $id = &#39;5&#39;; protected $version_date = &#39;2023-03-22 14:58:06&#39;; protected $version_user = &#39;Current User&#39;; protected $owner = NULL; protected $state = &#39;Online&#39;; protected $language = &#39;nl_NL&#39;; protected $shipment_id = NULL; protected $checkout_id = &#39;333050&#39;; protected $shipment_date = &#39;2023-01-27 11:30:06&#39;; protected $shipment_reference = &#39;SHIPMENT20232013x1&#39;; protected $shipmentnumber = &#39;3SAFWK987462289&#39;; protected $label_url = NULL; protected $tracktrace_url = NULL; protected $big_parcel = &#39;N&#39;; protected $only_recipient = &#39;N&#39;; protected $signature = &#39;N&#39;; protected $return_not_home = &#39;N&#39;; protected $age_check = &#39;N&#39;; protected $insured_amount = &#39;0.00&#39;; protected $shipment_state = &#39;REGISTERED&#39;; public $insert = FALSE; public $is_dummy = FALSE; protected $subitems = NULL; protected $pagebuilder_use = NULL; protected $content_pattern = &#39;/&lt;(h\\d|p|ul|ol|blockquote)(\\s[^&gt;]*|&gt;)(.*?)&lt;\\/(p|ul|ol)&gt;/s&#39;; protected $kind = &#39;default&#39;; protected $item_url = [...]; protected $Refines = [...]; protected $RefinesByGroup = [...]; protected $Images = [...]; protected $encoded_id = NULL; protected $active_extensions = [...]; protected $custom_screen_folder = NULL }]</span> )</td><td title='/projects/example-project-v1/src/application/classes/checkoutbulk/mvc/Controller.php' bgcolor='#eeeeec'>.../Controller.php<b>:</b>173</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.1376</td><td bgcolor='#eeeeec' align='right'>7735648</td><td bgcolor='#eeeeec'>Firstred\PostNL\PostNL->generateLabels( <span>$shipments = </span><span>[0 =&gt; class Firstred\PostNL\Entity\Shipment { protected $Addresses = [...]; protected $Amounts = NULL; protected $Barcode = &#39;3SAFWK987454071&#39;; protected $CollectionTimeStampEnd = NULL; protected $CollectionTimeStampStart = NULL; protected $Contacts = NULL; protected $Content = NULL; protected $CostCenter = NULL; protected $CustomerOrderNumber = NULL; protected $Customer = NULL; protected $Customs = NULL; protected $StatusCode = NULL; protected $PhaseCode = NULL; protected $DateFrom = NULL; protected $DateTo = NULL; protected $DeliveryAddress = NULL; protected $DeliveryTimeStampStart = NULL; protected $DeliveryTimeStampEnd = NULL; protected $DeliveryDate = NULL; protected $Dimension = class Firstred\PostNL\Entity\Dimension { ... }; protected $DownPartnerBarcode = NULL; protected $DownPartnerID = NULL; protected $DownPartnerLocation = NULL; protected $Events = NULL; protected $Groups = NULL; protected $IDExpiration = NULL; protected $IDNumber = NULL; protected $IDType = NULL; protected $OldStatuses = NULL; protected $ProductCodeCollect = NULL; protected $ProductCodeDelivery = &#39;3085&#39;; protected $ProductOptions = NULL; protected $ReceiverDateOfBirth = NULL; protected $Reference = NULL; protected $ReferenceCollect = NULL; protected $Remark = NULL; protected $ReturnBarcode = NULL; protected $ReturnReference = NULL; protected $id = &#39;f0579208-d7af-4fae-9cd6-e404caa4ecc4&#39;; protected $currentService = &#39;Labelling&#39; }, 1 =&gt; class Firstred\PostNL\Entity\Shipment { protected $Addresses = [...]; protected $Amounts = NULL; protected $Barcode = &#39;3SAFWK987419796&#39;; protected $CollectionTimeStampEnd = NULL; protected $CollectionTimeStampStart = NULL; protected $Contacts = NULL; protected $Content = NULL; protected $CostCenter = NULL; protected $CustomerOrderNumber = NULL; protected $Customer = NULL; protected $Customs = NULL; protected $StatusCode = NULL; protected $PhaseCode = NULL; protected $DateFrom = NULL; protected $DateTo = NULL; protected $DeliveryAddress = NULL; protected $DeliveryTimeStampStart = NULL; protected $DeliveryTimeStampEnd = NULL; protected $DeliveryDate = NULL; protected $Dimension = class Firstred\PostNL\Entity\Dimension { ... }; protected $DownPartnerBarcode = NULL; protected $DownPartnerID = NULL; protected $DownPartnerLocation = NULL; protected $Events = NULL; protected $Groups = NULL; protected $IDExpiration = NULL; protected $IDNumber = NULL; protected $IDType = NULL; protected $OldStatuses = NULL; protected $ProductCodeCollect = NULL; protected $ProductCodeDelivery = &#39;3085&#39;; protected $ProductOptions = NULL; protected $ReceiverDateOfBirth = NULL; protected $Reference = NULL; protected $ReferenceCollect = NULL; protected $Remark = NULL; protected $ReturnBarcode = NULL; protected $ReturnReference = NULL; protected $id = &#39;99270ce4-0091-4ee0-b41f-59c088d6ef88&#39;; protected $currentService = &#39;Labelling&#39; }, 2 =&gt; class Firstred\PostNL\Entity\Shipment { protected $Addresses = [...]; protected $Amounts = NULL; protected $Barcode = &#39;3SAFWK987447787&#39;; protected $CollectionTimeStampEnd = NULL; protected $CollectionTimeStampStart = NULL; protected $Contacts = NULL; protected $Content = NULL; protected $CostCenter = NULL; protected $CustomerOrderNumber = NULL; protected $Customer = NULL; protected $Customs = NULL; protected $StatusCode = NULL; protected $PhaseCode = NULL; protected $DateFrom = NULL; protected $DateTo = NULL; protected $DeliveryAddress = NULL; protected $DeliveryTimeStampStart = NULL; protected $DeliveryTimeStampEnd = NULL; protected $DeliveryDate = NULL; protected $Dimension = class Firstred\PostNL\Entity\Dimension { ... }; protected $DownPartnerBarcode = NULL; protected $DownPartnerID = NULL; protected $DownPartnerLocation = NULL; protected $Events = NULL; protected $Groups = NULL; protected $IDExpiration = NULL; protected $IDNumber = NULL; protected $IDType = NULL; protected $OldStatuses = NULL; protected $ProductCodeCollect = NULL; protected $ProductCodeDelivery = &#39;3085&#39;; protected $ProductOptions = NULL; protected $ReceiverDateOfBirth = NULL; protected $Reference = NULL; protected $ReferenceCollect = NULL; protected $Remark = NULL; protected $ReturnBarcode = NULL; protected $ReturnReference = NULL; protected $id = &#39;98f971f2-2917-4119-bc36-ae70b5b9065a&#39;; protected $currentService = &#39;Labelling&#39; }, 3 =&gt; class Firstred\PostNL\Entity\Shipment { protected $Addresses = [...]; protected $Amounts = NULL; protected $Barcode = &#39;3SAFWK987462289&#39;; protected $CollectionTimeStampEnd = NULL; protected $CollectionTimeStampStart = NULL; protected $Contacts = NULL; protected $Content = NULL; protected $CostCenter = NULL; protected $CustomerOrderNumber = NULL; protected $Customer = NULL; protected $Customs = NULL; protected $StatusCode = NULL; protected $PhaseCode = NULL; protected $DateFrom = NULL; protected $DateTo = NULL; protected $DeliveryAddress = NULL; protected $DeliveryTimeStampStart = NULL; protected $DeliveryTimeStampEnd = NULL; protected $DeliveryDate = NULL; protected $Dimension = class Firstred\PostNL\Entity\Dimension { ... }; protected $DownPartnerBarcode = NULL; protected $DownPartnerID = NULL; protected $DownPartnerLocation = NULL; protected $Events = NULL; protected $Groups = NULL; protected $IDExpiration = NULL; protected $IDNumber = NULL; protected $IDType = NULL; protected $OldStatuses = NULL; protected $ProductCodeCollect = NULL; protected $ProductCodeDelivery = &#39;3085&#39;; protected $ProductOptions = NULL; protected $ReceiverDateOfBirth = NULL; protected $Reference = NULL; protected $ReferenceCollect = NULL; protected $Remark = NULL; protected $ReturnBarcode = NULL; protected $ReturnReference = NULL; protected $id = &#39;afee1959-3318-40c9-a0c3-dedb930f2520&#39;; protected $currentService = &#39;Labelling&#39; }]</span>, <span>$printertype = </span><span>&#39;GraphicFile|PDF&#39;</span>, <span>$confirm = </span><span>TRUE</span>, <span>$merge = </span><span>TRUE</span>, <span>$format = </span><span>1</span>, <span>$positions = </span><span>[1 =&gt; TRUE, 2 =&gt; TRUE, 3 =&gt; TRUE, 4 =&gt; TRUE]</span>, <span>$a6Orientation = </span>??? )</td><td title='/projects/example-project-v1/src/application/classes/shipment/mvc/Mapper.php' bgcolor='#eeeeec'>.../Mapper.php<b>:</b>142</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.1379</td><td bgcolor='#eeeeec' align='right'>7750864</td><td bgcolor='#eeeeec'>Firstred\PostNL\Service\AbstractService->generateLabels( <span>[0 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE], 1 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE], 2 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE], 3 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE]]</span>, <span>TRUE</span> )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/PostNL.php' bgcolor='#eeeeec'>.../PostNL.php<b>:</b>1492</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.1379</td><td bgcolor='#eeeeec' align='right'>7751240</td><td bgcolor='#eeeeec'>Firstred\PostNL\Service\AbstractService->__call( <span>$name = </span><span>&#39;generateLabels&#39;</span>, <span>$args = </span><span>[0 =&gt; [0 =&gt; [...], 1 =&gt; [...], 2 =&gt; [...], 3 =&gt; [...]], 1 =&gt; TRUE]</span> )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/PostNL.php' bgcolor='#eeeeec'>.../PostNL.php<b>:</b>1492</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.1379</td><td bgcolor='#eeeeec' align='right'>7751664</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Service/AbstractService.php:125}' target='_new'>call_user_func_array:{/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Service/AbstractService.php:125}</a>( <span>$callback = </span><span>[0 =&gt; class Firstred\PostNL\Service\LabellingService { protected $postnl = class Firstred\PostNL\PostNL { ... }; public $ttl = NULL; public $cache = NULL }, 1 =&gt; &#39;generateLabelsRest&#39;]</span>, <span>$args = </span><span>[0 =&gt; [0 =&gt; [...], 1 =&gt; [...], 2 =&gt; [...], 3 =&gt; [...]], 1 =&gt; TRUE]</span> )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Service/AbstractService.php' bgcolor='#eeeeec'>.../AbstractService.php<b>:</b>125</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.1379</td><td bgcolor='#eeeeec' align='right'>7751736</td><td bgcolor='#eeeeec'>Firstred\PostNL\Service\LabellingService->generateLabelsREST( <span>$generateLabels = </span><span>[0 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE], 1 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE], 2 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE], 3 =&gt; [0 =&gt; class Firstred\PostNL\Entity\Request\GenerateLabel { ... }, 1 =&gt; TRUE]]</span>, <span>TRUE</span> )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Service/AbstractService.php' bgcolor='#eeeeec'>.../AbstractService.php<b>:</b>125</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.1405</td><td bgcolor='#eeeeec' align='right'>7901696</td><td bgcolor='#eeeeec'>Firstred\PostNL\HttpClient\HTTPlugClient->doRequests( <span>$requests = </span>??? )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Service/LabellingService.php' bgcolor='#eeeeec'>.../LabellingService.php<b>:</b>189</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.1411</td><td bgcolor='#eeeeec' align='right'>7992704</td><td bgcolor='#eeeeec'>Firstred\PostNL\Util\PendingPromise->wait( <span>$unwrap = </span><span>TRUE</span> )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/HttpClient/HTTPlugClient.php' bgcolor='#eeeeec'>.../HTTPlugClient.php<b>:</b>186</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>0.1411</td><td bgcolor='#eeeeec' align='right'>7992704</td><td bgcolor='#eeeeec'>Firstred\PostNL\Util\PendingPromise->waitIfPending(  )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/PendingPromise.php' bgcolor='#eeeeec'>.../PendingPromise.php<b>:</b>129</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>0.1411</td><td bgcolor='#eeeeec' align='right'>7992704</td><td bgcolor='#eeeeec'>Firstred\PostNL\Util\PendingPromise->invokeWaitFn(  )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/PendingPromise.php' bgcolor='#eeeeec'>.../PendingPromise.php<b>:</b>310</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>16</td><td bgcolor='#eeeeec' align='center'>0.1411</td><td bgcolor='#eeeeec' align='right'>7992704</td><td bgcolor='#eeeeec'>Firstred\PostNL\Util\EachPromise->Firstred\PostNL\Util\{closure:/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/EachPromise.php:150-167}( <span>TRUE</span> )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/PendingPromise.php' bgcolor='#eeeeec'>.../PendingPromise.php<b>:</b>338</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>17</td><td bgcolor='#eeeeec' align='center'>0.7408</td><td bgcolor='#eeeeec' align='right'>8083304</td><td bgcolor='#eeeeec'>Symfony\Component\HttpClient\Response\HttplugPromise->wait( <span>$unwrap = </span>??? )</td><td title='/projects/example-project-v1/src/vendor/firstred/postnl-api-php/src/Util/EachPromise.php' bgcolor='#eeeeec'>.../EachPromise.php<b>:</b>162</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>18</td><td bgcolor='#eeeeec' align='center'>0.7408</td><td bgcolor='#eeeeec' align='right'>8083304</td><td bgcolor='#eeeeec'>GuzzleHttp\Promise\Promise->wait( <span>$unwrap = </span><span>TRUE</span> )</td><td title='/projects/example-project-v1/src/vendor/symfony/http-client/Response/HttplugPromise.php' bgcolor='#eeeeec'>.../HttplugPromise.php<b>:</b>61</td></tr>
</table></font>

I have already tried to debug the code and skip the promise when `value` is `NULL`, but then I still get another exception that no label could be generated.
Could you help me fixing it or having a workaround?

Kind regards,
Erwin
ibizz

**Comment by firstred** [comment]
Looks like the PendingPromise utility class in this library hasn't kept up with updates in PHP itself, is my first guess.

What happens if you swap these 2 if(-else) blocks? https://github.com/firstred/postnl-api-php/blob/v1.3.x/src/Util/PendingPromise.php#L232-L247

I think the PostNL API returning an error in an undocumented format (there are plenty!), but it cannot be handled by the backwards compatible PendingPromise.

Work is currently being done on a PHP 8.0+ only version of the library, with updated utility classes, so that should fix the first error.

I would love to know the exact error response from the PostNL API. Are you able to log the responses? There is currently a problem with psr/log v3.0 compatibility, so it might be easier to attach a logger to the Httplug client instead: https://docs.php-http.org/en/latest/plugins/logger.html
